### ISSUE TITLE
Large margin

### ISSUE THREAD

**Issue by neocotic** [ajmath/Syntaxtic#4]
I'm seeing an ugly margin on all themes on Windows XP SP3 running Chrome 11.0.696.71. I've not tried another OS yet but can do later if required. I've tracked down the CSS responsible;

**shCore.css:61**

``` css
.syntaxhighlighter {
  margin: 1em 0 1em 0 !important;
  padding: 1px !important;
}
```

Suggested change:

``` css
.syntaxhighlighter {
  margin: 0 !important;
  padding: 0 !important;
}
```

However, the biggest whitespace exists because the _user agent stylesheet_ is declaring `margin: 8px`. Therefore, explicitly declaring the following somewhere should help;

``` css
body {
  margin: 0 !important;
  padding: 0 !important; /* Not required but covers all bases */
}
```

This could probably be done in **content_script.js:122**.
