### ISSUE TITLE
Floating gutter

### ISSUE THREAD

**Issue by neocotic** [ajmath/Syntaxtic#6]
It would be nice to see the gutter floating on the left of the page so that it's visible even if/when you scroll horizontally.

I have no suggestions how this could be done just now but it would definitely be a nice feature. However, I have done a little investigation and saw that this may not be so simple as the gutter itself is a table column and one that is generated within **shCore.js** so might involve a feature request for the SyntaxHighlighter project.

I've experimented a little bit in case you wanted to implement this yourself (if at all) and found that the following CSS change works well but requires some JavaScript changes too;

**shCore.css**

``` css
.syntaxhighlighter table {
  table-layout: fixed !important; /* Ensures content is kept within page width (incl. scroll bars) */
}
.syntaxhighlighter table td.code .container {
  overflow: auto !important; /* Ensures scroll bar is displayed only when needed */
  padding-bottom: 1px !important; /* Stops hanging letters being clipped by scroll bar (may need increased) */
}
```

Unfortunately, the downside of this is that some JavaScript will need to be called after **content_script.js:64** as well as any time the [window is resized](https://developer.mozilla.org/en/DOM/window.onresize). This JavaScript will be responsible for ensuring `.syntaxhighlighter table td.gutter` has `width: Npx !important` where _N_ is equal to the width of its last child `div`. Otherwise, the gutter won't appear at all as `table-layout: fixed` calculates the layout based on the column widths and not that of their contents. How this script looks I'll leave up to you.
